from cycle267_renderer import SCENE_DURATIONS, PUBLICATION_GATE, AUTO_POST
assert len(SCENE_DURATIONS)==8
assert sum(SCENE_DURATIONS)==15
assert len(set(SCENE_DURATIONS))>=3
assert SCENE_DURATIONS[0] <= SCENE_DURATIONS[2]
assert PUBLICATION_GATE=='HUMAN_REVIEW / PUBLICATION_NOT_APPROVED'
assert AUTO_POST is False
print('PASS cycle267')
